version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '7000:7000'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
  # docker-compose up

